language: node_js
services:
  - docker  
node_js:  
  - "8"
install:
  - docker pull mcr.microsoft.com/azure-storage/azurite
  - docker run -d -p 10000:10000 mcr.microsoft.com/azure-storage/azurite azurite-blob --blobHost 0.0.0.0